print("mouse")
print("cat")
print("dog")
print("pig")
print("cow")
print("sheep")
print("buffalo")
print("fish")
print("duck")
print("chicken")
print("lion")
print("cheehtah")
print("tiger")
print("wolf")
# print("rabbit")
# print("fox")
# print("raindeer")
# print("bird")
# print("unicorn")
# print("bear")
# print("koala")