print("typing test")
print("chess")
print("sudoku")
print("space shooter")
print("space invader")
print("Snake")
print("tetris")
print("Arkanoid")
print("terraria")
print("minesweeper")
print("tower defender")